### ISSUE TITLE
Unable to create validator

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-ledger#32]
I'm sure it's my fault again but I can't use `poa create-validator`.

I get

```shell
failed to execute message; message index: 0: invalid validator address:
  hrp does not match bech32 prefix: expected ''cosmosvaloper'' got ''manifestvaloper'':
  internal logic error: invalid address'
```

my `validator.json` file is

```json
{
  "pubkey": {
    "@type": "/cosmos.crypto.ed25519.PubKey",
    "key": "80AgXOAcfNhcEpclCS4RqGaihegwB3tpb2qF+KVnBwM="
  },
  "amount": "1stake",
  "moniker": "occidolumen",
  "commission-rate": "0.0",
  "commission-max-rate": "0.2",
  "commission-max-change-rate": "0.01",
  "min-self-delegation": "1"
}
```

**Comment by Reecepbcups** [comment]
looking into

**Comment by Reecepbcups** [comment]
This is a POA v0.0.1-alpha.3 issue, and was fixed in the main v0.50.0 release

so this is testnet only issue sadly, as I caught it upstream after me and Chalabi launched this testnet

**Comment by fmorency** [comment]
> This is a POA v0.0.1-alpha.3 issue, and was fixed in the main v0.50.0 release
> 
> so this is testnet only issue sadly, as I caught it upstream after me and Chalabi launched this testnet

What would we need for us to join as validators? A new testnet?

**Comment by Reecepbcups** [comment]
either a new testnet, or me and chalabi need to halt at a height, change the binary to main, and start.
Then you could sync with the current binary to that height, stop, use the new binary, and join the set.

**Comment by chalabi2** [comment]
@Reecepbcups After launching a new testnet, we are still getting the error 

```
failed to execute message; message index: 0: invalid validator address:
  hrp does not match bech32 prefix: expected ''cosmosvaloper'' got ''manifestvaloper'':
  internal logic error: invalid address'
  ```

**Comment by chalabi2** [comment]
This was fixed in #42
